### ISSUE TITLE
Make salt value come from settings

### ISSUE THREAD

**Issue by pantunes** [aekazitt/fastapi-csrf-protect#2]
The `salt` should not be hard-coded:
https://github.com/aekazitt/fastapi-csrf-protect/blob/3f19f2ca0ec7ac569e4df5c10e68d6cbfaa5e385/fastapi_csrf_protect/core.py#L112

Is it possible to get it from the settings/config?

**Comment by aekazitt** [comment]
I lifted off from Flask-WTF in that regard... 

https://github.com/lepture/flask-wtf/search?q=salt

Do you want to have the ability to change the salt in CsrfConfig? I think that can be managed.

**Comment by aekazitt** [comment]
Referencing Moderator's response of WTForms when asking for salt to be configurable...

https://github.com/wtforms/flask-wtf/issues/385

v
```
In itsdangerous, the salt parameter is somewhat misnamed, and is not intended as a salt for defeating cracking.
```

I'll leave the salt hard-coded. Closing issue.
