### ISSUE TITLE
cookies dont work.

### ISSUE THREAD

**Issue by Nebulizer1213** [aekazitt/fastapi-csrf-protect#6]
i am trying to send a post request to my api from my website. I get this error.
Forbidden (403)
CSRF verification failed. Request aborted.

You are seeing this message because this site requires a CSRF cookie when submitting forms. This cookie is required for security reasons, to ensure that your browser is not being hijacked by third parties.

If you have configured your browser to disable cookies, please re-enable them, at least for this site, or for 'same-origin' requests.

I did csrf_protect.set_csrf_cookie(response) in the function sending the request and in the function receiving the request in the api. It did not change and i still get the error. Also please make some type of way for people to get support. Like a discord server. There is also a error in your documentation. In the docs it says to do this csrf_protect.set_csrf_cookie(request) when it is supposed to be csrf_protect.set_csrf_cookie(response).

**Comment by Nebulizer1213** [comment]
https://pastecord.com/ykicadivol.py

**Comment by aekazitt** [comment]
You're using `set_csrf_cookie` twice in both GET and POST endpoints;
Try using `set_csrf_cookie` in GET endpoint and `validate_csrf_in_cookies` in POST endpoint.
See  example on README for details.

**Comment by Nebulizer1213** [comment]
when you say get endpoint do you mean the code at the bottom of the pastecord I sent?

**Comment by Nebulizer1213** [comment]
https://pastecord.com/ewisabacyb.py i no longer get the error i sent before. I now get this {"detail":"Missing Cookie fastapi-csrf-token"}
