### ISSUE TITLE
403 forbidden happening again

### ISSUE THREAD

**Issue by Nebulizer1213** [aekazitt/fastapi-csrf-protect#8]
Sorry for all of the issues I have been opening. I am new to web development and I don't know much about cookies and stuff. 
this is my new code. https://pastecord.com/ogazewokiw.py and I am getting the original error again.

**Comment by aekazitt** [comment]
No idea. Please go to `StackOverflow` with your questions.

**Comment by Nebulizer1213** [comment]
i figured it out. The api is on port 83 so i made the domain redirect to http://myip:83 with go daddy. It seems that was the problem because going to http://myip:83 works fine.
